from enum import Enum:

class ComplexityLevel(Enum):
    BEGINNER = "BEGINNER"
    INTERMEDIATE = "INTERMEDIATE"
    ADVANCED = "ADVANCED"

class Visibility(Enum):
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"

class SkillCategory(Enum):
    BEHAVIOURAL = "BEHAVIOURAL"
    TECHNICAL = "TECHNICAL"
    LANGUAGE = "LANGUAGE"
    COGNITIVE = "COGNITIVE"

class OptionType(Enum):
    SINGLEANSWER = "SINGLE ANSWER"
    MULTIPLEANSWERS = "MULTIPLEANSWERS"
    TRUEORFALSE = "TRUEORFALSE"
    FREETEXT = "FREETEXT"
    FILEUPLOAD = "FILEUPLOAD"
    LINEARSCALE = "LINEARSCALE"
