from enum import Enum

class ComplexityLevel(Enum):
    BEGINNER = "BEGINNER"
    INTERMEDIATE = "INTERMEDIATE"
    ADVANCED = "ADVANCED"

class Visibility(Enum):
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"

class SkillCategory(Enum):
    BEHAVIOURAL = "BEHAVIOURAL"
    TECHNICAL = "TECHNICAL"
    LANGUAGE = "LANGUAGE"
    COGNITIVE = "COGNITIVE"

class OptionType(Enum):
    SINGLE_ANSWER = "SINGLE_ANSWER"
    MULTIPLE_ANSWERS = "MULTIPLE_ANSWERS"
    TRUE_OR_FALSE = "TRUE_OR_FALSE"
    FREE_TEXT = "FREE_TEXT"
    FILE_UPLOAD = "FILE_UPLOAD"
    LINEAR_SCALE = "LINEAR_SCALE"
